# docker-compose configuration file for account-verification-node# docker-compose configuration file for appointment-reminders-django

web:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src/app
  links:
    - mongo
  environment:
    - TWILIO_ACCOUNT_SID
    - TWILIO_AUTH_TOKEN
    - TWILIO_NUMBER
    - MONGO_URL
    - AUTHY_API_KEY

mongo:
  image: mongo:3.0